param(
    [string]$TaskName = "ChimeraMemoryHttpMcp",
    [string]$HostName = "127.0.0.1",
    [int]$Port = 8766,
    [int]$EmbeddingThreads = 4,
    [int]$EmbedBatchLimit = 128,
    [int]$EmbedBatchSize = 32,
    [ValidateSet("auto", "scheduled_task", "startup_folder")]
    [string]$Mode = "auto",
    [switch]$RunNow,
    [switch]$Remove
)

$ErrorActionPreference = "Stop"
$RepoRoot = Split-Path -Parent $PSScriptRoot
$StartScript = Join-Path $PSScriptRoot "start-cm-http.ps1"
$StartupCmd = Join-Path ([Environment]::GetFolderPath("Startup")) "$TaskName.cmd"

function Install-StartupFolderCommand {
    $cmd = @"
@echo off
rem ChimeraMemory shared HTTP MCP startup. Generated by scripts\install-cm-http-autostart.ps1.
start "" /min powershell.exe -NoProfile -WindowStyle Hidden -ExecutionPolicy Bypass -File "$StartScript" -HostName $HostName -Port $Port -EmbeddingThreads $EmbeddingThreads -EmbedBatchLimit $EmbedBatchLimit -EmbedBatchSize $EmbedBatchSize -Bootstrap
"@
    Set-Content -Path $StartupCmd -Value $cmd -Encoding ascii
    Write-Host "Registered Startup folder command: $StartupCmd"
    if ($RunNow) {
        Start-Process -FilePath "powershell.exe" `
            -ArgumentList @(
                "-NoProfile",
                "-WindowStyle", "Hidden",
                "-ExecutionPolicy", "Bypass",
                "-File", $StartScript,
                "-HostName", $HostName,
                "-Port", [string]$Port,
                "-EmbeddingThreads", [string]$EmbeddingThreads,
                "-EmbedBatchLimit", [string]$EmbedBatchLimit,
                "-EmbedBatchSize", [string]$EmbedBatchSize,
                "-Bootstrap"
            ) `
            -WorkingDirectory $RepoRoot `
            -WindowStyle Hidden | Out-Null
        Write-Host "Started Startup folder command target: $TaskName"
    }
}

if ($Remove) {
    Unregister-ScheduledTask -TaskName $TaskName -Confirm:$false -ErrorAction SilentlyContinue
    Remove-Item -LiteralPath $StartupCmd -Force -ErrorAction SilentlyContinue
    Write-Host "Removed scheduled task: $TaskName"
    Write-Host "Removed Startup folder command: $StartupCmd"
    exit 0
}

if (-not (Test-Path $StartScript)) {
    throw "Missing CM HTTP startup script: $StartScript"
}

$quotedStartScript = '"' + $StartScript + '"'
$arguments = @(
    "-NoProfile",
    "-WindowStyle", "Hidden",
    "-ExecutionPolicy", "Bypass",
    "-File", $quotedStartScript,
    "-HostName", $HostName,
    "-Port", [string]$Port,
    "-EmbeddingThreads", [string]$EmbeddingThreads,
    "-EmbedBatchLimit", [string]$EmbedBatchLimit,
    "-EmbedBatchSize", [string]$EmbedBatchSize,
    "-Bootstrap"
) -join " "

$action = New-ScheduledTaskAction `
    -Execute "powershell.exe" `
    -Argument $arguments `
    -WorkingDirectory $RepoRoot
$trigger = New-ScheduledTaskTrigger -AtLogOn
$settings = New-ScheduledTaskSettingsSet `
    -AllowStartIfOnBatteries `
    -DontStopIfGoingOnBatteries `
    -ExecutionTimeLimit (New-TimeSpan -Days 365) `
    -MultipleInstances IgnoreNew `
    -RestartCount 3 `
    -RestartInterval (New-TimeSpan -Minutes 1) `
    -StartWhenAvailable

if ($Mode -eq "startup_folder") {
    Install-StartupFolderCommand
    exit 0
}

try {
    Register-ScheduledTask `
        -TaskName $TaskName `
        -Action $action `
        -Trigger $trigger `
        -Settings $settings `
        -Description "Start the ChimeraMemory shared HTTP MCP server from its repo-local venv." `
        -Force | Out-Null

    Write-Host "Registered scheduled task: $TaskName"
    if ($RunNow) {
        Start-ScheduledTask -TaskName $TaskName
        Write-Host "Started scheduled task: $TaskName"
    }
} catch {
    if ($Mode -eq "scheduled_task") {
        throw
    }
    Write-Host "Scheduled task registration failed; falling back to Startup folder command."
    Install-StartupFolderCommand
}
